version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    
  # frontend:
  #   build:
  #     context: ./frontend/vite-project
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=https://git-me-ai-v1.onrender.com
  #     - VITE_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
  #   volumes:
  #     - ./frontend/vite-project:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
